name: Deploy Node App to Azure App Service

on:
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-latest

```
permissions:
  id-token: write
  contents: read

steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: '18'

  - name: Install dependencies
    working-directory: ./app
    run: npm install

  - name: Azure Login
    uses: azure/login@v2
    with:
      client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BFBD17D0184248F68BF6690A4B92EDA9 }}
      tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B1C56B7682CF4B3DBD1570B37537DB21 }}
      subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1882FD26CBBC43BB9F049860AC4C4277 }}

  - name: Deploy to Azure Web App
    uses: azure/webapps-deploy@v3
    with:
      app-name: anson-webapp-demo
      package: ./app
```
